language: python
sudo: false
python:
  - 2.7
env:
  matrix:
  - TEST_SPHINX="yes"
addons:
  apt:
    packages:
      - texlive-fonts-recommended
      - texlive-latex-extra
      - texlive-fonts-extra
      - texlive-latex-recommended
      - dvipng
before_install:
  - pip install "sphinx==1.2b3";
script:
  - bin/test_travis.sh
notifications:
  email: false
